name: Build, Check & Publish

on:
  push:
    branches:
      - 'feature/**'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${GITHUB_REF}
          fetch-depth: 0
      - name: Dockerfile lint using Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile