name: Build, Check & Publish

on:
  push:
    branches:
      - 'feature/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${GITHUB_SHA}
      - run: ls
      - name: Dockerfile lint using Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile